/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  swotSidebar: [
    'intro',
    {
      type: 'category',
      label: '📊 SWOT-анализы',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'SWOT-анализы',
        description: 'Все SWOT-анализы',
      },
      items: [{type: 'autogenerated', dirName: 'swot'}],
    },
    {
      type: 'category', 
      label: '🔄 Сравнения',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Сравнения',
        description: 'Сравнения появятся после второго анализа',
      },
      items: [{type: 'autogenerated', dirName: 'comparisons'}],
    },
  ],
};

export default sidebars;
